# Base configuration
baseURL = "https://huawei.github.io/css-docs/"
title = "Huawei"
copyright = "版权所有 © 华为技术有限公司 2025。保留一切权利。"
contentDir = "content/zh-cn"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true
prism_syntax_highlighting = true
enableRobotsTXT = true
enableGitInfo = true
# Disable categories & tags
disableKinds = ["taxonomy", "term"]
# GitHub Information
github_repo = "https://github.com/Huawei/eSDK_K8S_Plugin"
github_project_repo = "https://github.com/Huawei/eSDK_K8S_Plugin"
github_branch = "master"

# Configure how URLs look like per section
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Configure search engine
[params]
offlineSearch = true

# Language configuration
[languages]
[languages.zh-cn]
languageName = "简体中文"
# contentDir = "content/zh-cn"
languageCode = "zh-cn"
weight = 1
[languages.zh-cn.params]
title = "华为CSS"
description = "华为容器存储套件"
version_menu = "版本"

[languages.en]
languageName ="English"
# contentDir = "content/en"
languageCode = "en"
weight = 2
copyright = "Copyright © 2025 Huawei Technologies Co., Ltd. All rights reserved."
[languages.en.params]
title = "Huawei CSS"
description = "Huawei Container Storage Suite"
version_menu = "Releases"
[[languages.en.params.versions]]
version = "v4.6.0 (current)"
url = "http://huawei.github.io/css-docs/en/docs"
[[languages.en.params.versions]]
version = "v4.5.0"
url = "http://huawei.github.io/css-docs/en/v4.5.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "catppuccin-latte"
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    guessSyntax = "true"

# Comment out if you don't want the "print entire section" link enabled
[outputs]
section = ["HTML", "print", "RSS"]

[params.ui]
# Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
sidebar_menu_foldable = true
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
showLightDarkModeMenu = false

[[params.versions]]
version = "v4.6.0（当前版本）"
url = "http://huawei.github.io/css-docs/docs"
[[params.versions]]
version = "v4.5.0"
url = "http://huawei.github.io/css-docs/v4.5.0"

[[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/Huawei/eSDK_K8S_Plugin"

[params.links]
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/Huawei/eSDK_K8S_Plugin"
  icon = "fab fa-github"
  desc = "Development takes place here!"

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.mounts]]
    source = "content/en"
    target = "content"
    lang = "en"
  [[module.mounts]]
    source = "content/zh-cn"
    target = "content"
    lang = "zh-cn"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
