name: Deployment to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main  # <-- specify the branch you want to deploy from
  pull_request:

env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.129.0'
          extended: true

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.1'

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci

      - run: hugo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }} # <-- specify same branch as above here
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
